# Generated by Django 3.2.22 on 2023-10-09 04:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_image',
            field=models.ImageField(null=True, upload_to=core.models.background_image_file_path),
        ),
    ]
