# Generated by Django 3.2.22 on 2023-10-10 00:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature_image',
            field=models.ImageField(null=True, upload_to=core.models.signature_image_file_path),
        ),
    ]
